// <auto-generated />
using System;
using API_ProyectoP1_Gimnasio_ProgramacionIV.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_ProyectoP1_Gimnasio_ProgramacionIV.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20231025004422_CreacionTablas")]
    partial class CreacionTablas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API_ProyectoP1_Gimnasio_ProgramacionIV.Models.Membresia", b =>
                {
                    b.Property<int>("idMembresia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idMembresia"));

                    b.Property<int>("duracionMembresia")
                        .HasColumnType("int");

                    b.Property<string>("nombreMembresia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("precioMembresia")
                        .HasColumnType("float");

                    b.HasKey("idMembresia");

                    b.ToTable("Membresia");
                });

            modelBuilder.Entity("API_ProyectoP1_Gimnasio_ProgramacionIV.Models.Miembro", b =>
                {
                    b.Property<int>("idMiembro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idMiembro"));

                    b.Property<string>("apellidoMiembro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("emailMiembro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("fechaInscripcion")
                        .HasColumnType("datetime2");

                    b.Property<string>("nombreMiembro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idMiembro");

                    b.ToTable("Miembro");

                    b.HasData(
                        new
                        {
                            idMiembro = 1,
                            apellidoMiembro = "Almeida",
                            emailMiembro = "oscar.almedia@udla.edu.ec",
                            fechaInscripcion = new DateTime(2023, 10, 24, 19, 44, 22, 649, DateTimeKind.Local).AddTicks(914),
                            nombreMiembro = "Oscar"
                        },
                        new
                        {
                            idMiembro = 2,
                            apellidoMiembro = "Toscano",
                            emailMiembro = "diego.toscano@udla.edu.ec",
                            fechaInscripcion = new DateTime(2023, 10, 24, 19, 44, 22, 649, DateTimeKind.Local).AddTicks(930),
                            nombreMiembro = "Diego"
                        });
                });

            modelBuilder.Entity("API_ProyectoP1_Gimnasio_ProgramacionIV.Models.Pago", b =>
                {
                    b.Property<int>("idPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idPago"));

                    b.Property<DateTime>("fechaPago")
                        .HasColumnType("datetime2");

                    b.Property<int>("miembroId")
                        .HasColumnType("int");

                    b.Property<double>("montoPago")
                        .HasColumnType("float");

                    b.HasKey("idPago");

                    b.ToTable("Pago");
                });

            modelBuilder.Entity("API_ProyectoP1_Gimnasio_ProgramacionIV.Models.Visita", b =>
                {
                    b.Property<int>("idVisita")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idVisita"));

                    b.Property<string>("descripcionVisita")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("fechaVisita")
                        .HasColumnType("datetime2");

                    b.Property<int>("miembroId")
                        .HasColumnType("int");

                    b.HasKey("idVisita");

                    b.ToTable("Visita");
                });
#pragma warning restore 612, 618
        }
    }
}
